// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Wuvist/decho/controller"
)

// Injectors from wire.go:

func getWebApp() (*WebApp, error) {
	echo := newEcho()
	config, err := loadTomlConf()
	if err != nil {
		return nil, err
	}
	string2 := newMsg()
	blogController, err := controller.NewBlogController(echo, string2)
	if err != nil {
		return nil, err
	}
	webApp := &WebApp{
		Echo:   echo,
		config: config,
		blog:   blogController,
	}
	return webApp, nil
}
