// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Wuvist/decho/controller"
)

// Injectors from wire.go:

func getWebApp() (*WebApp, error) {
	config, err := loadTomlConf()
	if err != nil {
		return nil, err
	}
	echo := newEcho()
	string2 := newMsg()
	blogController, err := controller.NewBlogController(echo, string2)
	if err != nil {
		return nil, err
	}
	webApp := newWebApp(config, echo, blogController)
	return webApp, nil
}
