// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Articles           string
	Blogger            string
	Comment            string
	Links              string
	Userdefinecategory string
}{
	Articles:           "articles",
	Blogger:            "blogger",
	Comment:            "comment",
	Links:              "links",
	Userdefinecategory: "userdefinecategory",
}
